@startuml Administrar Equipos 
actor "Cliente" as Administrador 
boundary boundary
control control
collections Firestore as Usuarios 
Administrador->boundary: gestionarEquipos()
activate boundary
boundary->control:GestionarEquipos()
activate control
control->Usuarios:getEquipos()
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary

Administrador->boundary: enviar(Datos)
activate boundary
boundary->control:Gestiona(datos)
activate control
control->Usuarios:modificar(Datos)
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary


opt Crear Equipo
    Administrador->boundary: CrearEquipo()
    activate boundary
    boundary->control:CrearEquipo()
    activate control
    boundary<-control:datos=obtenerDatos()
    activate boundary
    boundary-->>control
    deactivate boundary
    control->Usuarios:CrearEquipo()
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <<-- control
    deactivate control
    Administrador<<--boundary
    deactivate boundary
end


opt consultar Equipo
    Administrador->boundary: conusltarEquipo(Equipo)
    activate boundary
    boundary->control:conusltarEquipo(Equipo)
    activate control
    control->Usuarios:datos=ConsultarEquipo(Equipo)
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <- control:mostarDatos(datos)
    activate boundary
    boundary-->>control
    deactivate boundary
    deactivate control
    deactivate boundary
end


opt eliminar Equipo
    Administrador->boundary: EliminarEquipo(Equipo)
    activate boundary
    boundary->control:EliminarEquipo(Equipo)
    activate control
    boundary<-control:ConfirmarEliminar()
    activate boundary
    boundary-->>control
    deactivate boundary
    control->Usuarios:Eliminar(Equipo)
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <<-- control
    deactivate control
    Administrador<<--boundary
    deactivate boundary
end


@enduml