@startuml Administrar perfil
actor "User" as Administrador
boundary boundary
control control
collections Usuarios as Usuarios 
participant "Usuario" as user
Administrador->boundary: gestionarCuentas()
activate boundary
boundary->control:GestionarCuentas()
activate control
control->Usuarios:getCuenta()
activate Usuarios
Usuarios->user:getCuenta()
activate user
Usuarios<<--user
deactivate user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary

Administrador->boundary: enviar(Datos)
activate boundary
boundary->control:Gestionarcuenta(datos)

activate control
control->Usuarios:modificar(Datos)
activate Usuarios
Usuarios->user:modificar(Datos)
activate user
Usuarios<<--user
deactivate user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary
@enduml