@startuml Editar usuario
actor "Administrador" as Administrador
boundary boundary
control control
collections Premios as Usuarios 
participant ":Premio" as user
Administrador->boundary: crearPremio(datos)
activate boundary
boundary->control:crearPremio(datos)
activate control
control->Usuarios:crearPremio(datos)
activate Usuarios
create user
Usuarios->user: <create>>
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
@enduml