@startuml
node "Ordenador" as Ordenador <<Client Device>>{
    component "navegador Web"  as browser   
}

node "Servidor UNIX" as Servidor  <<Device>>{
    component "Servidor Web"{
        component "Route66" as app
    }
}
cloud internet{
database "Firebase" as firebase {
        component "Firestore" as firesotre
        component "Firebase Storage" as storage
        component "Firebase auth" as auth
    }
}
browser-down--app
app-down--firebase
@enduml
