
@startuml teams

package pkj <<Frame>> {
  class App

  package Firebase #ff9801{
    class  Firebase.Firestore
    class  Firebase.Auth
    class  Firebase.Storage
    }

  package components #41b883{
    class Navbar
    class Canvasmap
    class EquiposUsuario
    class GestionEquipo
    class HelloWorld
    class Info
    class ListaInsignias
    class ListaLogros
    class ListaMisiones
    class ListaPremios
    class ListaUsuarios
    class Login
    class ModificarPerfil
    class PremiosUsuario
    class Ranking
    class SignUp
    class UserManagement
    }
  package store <<Vuex>> #41b883{
    class  store.User{
      id:String
      name:String
      email:String
      photoUrl:String
      nivel:int
      puntos:int 
      rol:String 
      getUser()
      updateUser()
      clearUser()
    }
  }  
  package router <<router>> #41b883{
    class  router.Index
  }
  App -right-> router.Index
  router.Index -right-->components
  router.Index -down-> store
  components -down-> store
  components --> Firebase.Firestore
  components --> Firebase.Storage 
  store --> Firebase.Auth
  Canvasmap--o HelloWorld
 

  }

hide empty members   
hide circle
skinparam classAttributeIconSize 0
@enduml