@startuml Editar Insignia
actor "Administrador" as Administrador
boundary boundary
control control
collections Insignias as Usuarios 
participant ":Insignia" as user
Administrador->boundary: editarInsignia(datos)
activate boundary
boundary->control:editarInsignia(datos)
activate control
control->Usuarios:editarInsignia(datos)
activate Usuarios
Usuarios->user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
deactivate boundary
@enduml