@startuml Editar Premio
actor "Administrador" as Administrador
boundary boundary
control control
collections Premios as Usuarios 
participant ":Premio" as user
Administrador->boundary: editarPremio(datos)
activate boundary
boundary->control:editarPremio(datos)
activate control
control->Usuarios:editarPremio(datos)
activate Usuarios
Usuarios->user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
deactivate boundary
@enduml