@startuml Editar Logro
actor "Administrador" as Administrador
boundary boundary
control control
collections Logros as Usuarios 
participant ":Logro" as user
Administrador->boundary: editarLogro(datos)
activate boundary
boundary->control:editarLogro(datos)
activate control
control->Usuarios:editarLogro(datos)
activate Usuarios
Usuarios->user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
deactivate boundary
@enduml