@startuml Eliminar Logro
actor "Administrador" as Administrador
boundary boundary
control control
collections Logros as Usuarios 
participant ":Logro" as user
Administrador->boundary: eliminarLogro(datos)
activate boundary
boundary->control:eliminarLogro(datos)
activate control
control->Usuarios:eliminarLogro(datos)
activate Usuarios
Usuarios->x user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
deactivate boundary
@enduml