@startuml Eliminar Insignia
actor "Administrador" as Administrador
boundary boundary
control control
collections Insignias as Usuarios 
participant ":Insignia" as user
Administrador->boundary: eliminarInsignia(datos)
activate boundary
boundary->control:eliminarInsignia(datos)
activate control
control->Usuarios:eliminarInsignia(datos)
activate Usuarios
Usuarios->x user
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
deactivate boundary
@enduml