
@startuml Insignias

package Insignias <<Frame>> {
 class FirebaseStorageFile {
    - fileName : String = insignias/{teamId}
}

 class Insignias <<Collection>>
 class Insignia <<Document>>{
     - id: String
     - name: String
     - /avatar:String
     - /avatarRef: String    
 }


 FirebaseStorageFile "0..1"<--"1"Insignias
 Insignias*-"0..*" Insignia
}

hide empty members   
hide circle
skinparam classAttributeIconSize 0
@enduml