
@startuml Missions

package Missions <<Frame>> {
 class FirebaseStorageFile {
    - fileName : String = {avatarRef}
}


class Levels <<Collection>>
 class Level <<Document>>{
     - id: String
     - name: String
     - level: int
     - /avatar:String
     - /avatarRef: String    
 }

 class Missions <<Collection>>
 class Mission <<Document>>{
     - id: String
     - name: String
     - /avatar:String
     - /avatarRef: String    
 }


 FirebaseStorageFile "0..1"<-up-Mission
 FirebaseStorageFile "0..1"<-up-Level
Levels*-- Level
 Missions*-left- Mission
Level"1"*-down-"0..1" Missions
}

hide empty members   
hide circle
skinparam classAttributeIconSize 0
@enduml