@startuml GestionarCuenta
actor "Administrador" as Administrador 
boundary boundary
control control
collections Usuarios as Usuarios 
Administrador->boundary: gestionarCuentas()
activate boundary
boundary->control:GestionarCuentas()
activate control
control->Usuarios:getCuentas()
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary

Administrador->boundary: enviar(Datos)
activate boundary
boundary->control:GestionarCuenta(datos)
activate control
control->Usuarios:modificar(Datos)
control<<--Usuarios
deactivate Usuarios
boundary<<--control
deactivate control
Administrador<<--boundary
deactivate boundary


opt Crear Cuenta
    Administrador->boundary: CrearCuenta()
    activate boundary
    boundary->control:CrearCuenta()
    activate control
    boundary<-control:datos=obtenerDatos()
    activate boundary
    boundary-->>control
    deactivate boundary
    control->Usuarios:CrearCuenta()
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <<-- control
    deactivate control
    Administrador<<--boundary
    deactivate boundary
end


opt consultar Cuenta
    Administrador->boundary: conusltarCuenta(Cuenta)
    activate boundary
    boundary->control:conusltarCuenta(Cuenta)
    activate control
    control->Usuarios:datos=ConsultarCuenta(Cuenta)
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <- control:mostarDatos(datos)
    activate boundary
    boundary-->>control
    deactivate boundary
    deactivate control
    deactivate boundary
end


opt eliminar Cuenta
    Administrador->boundary: EliminarCuenta(Cuenta)
    activate boundary
    boundary->control:EliminarCuenta(Cuenta)
    activate control
    boundary<-control:ConfirmarEliminar()
    activate boundary
    boundary-->>control
    deactivate boundary
    control->Usuarios:Eliminar(Cuenta)
    activate Usuarios
    control<<--Usuarios
    deactivate Usuarios
    boundary <<-- control
    deactivate control
    Administrador<<--boundary
    deactivate boundary
end


@enduml