
@startuml teams

package teams <<Frame>> {
 class FirebaseStorageFile {
    - fileName : String = {avatarRef}
}

 class Teams <<Collection>>
 class Team <<Document>>{
     - Id: String
     - name: String
     - /nombre: String
     - /avatar:String
     - /avatarRef:String
     - admin: String

 }

 class TeamMembers <<Collection>>
 class TeamAchivements <<Collection>>
 class TeamInsignias <<Collection>>
 class TeamInsignia <<Document>>{
     - id:string
     - oid: int    
 }
 class TeamAchivement<<Document>>{
     - id:string
     - oid: String
 }
 class TeamMember<<Document>>{
     - id:String
 }
 FirebaseStorageFile "0..1"<--"1"Team
 Teams*-"0..*" Team
 Team*--"0..1"TeamMembers
 Team*--"0..1"TeamAchivements 
 Team*--"0..1"TeamInsignias
 TeamInsignias*--"0..1"TeamInsignia
 TeamAchivements*--"0..1"TeamAchivement
 TeamMembers*--"0..1"TeamMember

}



hide empty members   
hide circle
skinparam classAttributeIconSize 0
@enduml