@startuml use cases
left to right direction
skinparam packageStyle rectangle
:Usuario: as user
:cliente: as client
:Administrador: as admin
user<|--client 
user<|- admin
rectangle route66 {
client --> (consultar equipo)
client --> (crear equipo)
client --> (editar equipo)
client --> (eliminar equipo)
client --> (invitar a equipo)
client --> (eliminar de un equipo)
client --> (salir de un equipo)
client--> (Mostrar puntos)
client--> (Mostrar misiones)
client --> (Mostrar insignias)
client --> (Mostrar logros)
client --> (Mostrar premios)
client --> (Mostrar progreso)
}
@enduml
