@startuml use cases
left to right direction
skinparam packageStyle rectangle
:Usuario: as user
:cliente: as client
:Administrador: as admin
user<|-client 
user<|-- admin
rectangle route66 {


admin -->(editar usuario)
admin -->(Crear Nivel)
admin -->(Editar Nivel)
admin -->(Eliminar Nivel)
admin -->(Crear misión)
admin -->(Editar misión)
admin -->(Eliminar misión)

admin -->(Crear Logro)
admin -->(Editar Logro)
admin -->(Eliminar Logro)


admin -->(Crear Insignia)
admin -->(Editar Insignia)
admin -->(Eliminar Insignia)

admin -->(Crear Premio)
admin -->(Editar Premio)
admin -->(Eliminar Premio)

}
@enduml
