@startuml users
package users <<Frame>> {
 class FirebaseStorageFile <<FirebaseStorage>>{
- fileName : String = {avatarRef}
}
    class FirebaseUser <<FirebaseAuthentication>>{
        - userId : String
        - email : String
        - visibleName : String 
    }
    class FirebaseConnection <<FirebaseAuthentication>>
    class EmailPassword <<FirebaseAuthentication>>

 class Users <<Collection>>
 
 class User <<Document>>{
    - <<Key>>/userid: String
    - nombre: String
    - fechanacimiento:LocalDate
    - correoElectronico: String  
    - puntos: long
    - level: int
    - rol: String 
 }
 

together {
 class UserMissions <<Collection>>
 class UserInsignias <<Collection>>
 class UserAchivements <<Collection>>
 class UserPrizes <<Collection>>
 class UserInsignia <<Document>>{
      -id:String
     -oid:String
 }
 class UserAchivement<<Document>>{
      -id:String
     -oid:String
 }
 class UserPrize<<Document>>{
     -id:String
     -oid:String
}
 class UserMission <<Document>>{
     -id:String
     -oid:String
     -done:boolean
     -points: int
}
}


 User*--"0..1"UserMissions
 User*--"0..1"UserAchivements
 User*--"0..1"UserInsignias 
 User*--"0..1"UserPrizes
UserMissions*--"0..1"UserMission
UserAchivements*--"0..1"UserAchivement
UserInsignias*--"0..1"UserInsignia
UserPrizes*--"0..1"UserPrize
FirebaseUser*-"1..2"FirebaseConnection
FirebaseUser <-- User
FirebaseStorageFile"0..1"<--"1"User
Users*-"0..*" User

FirebaseConnection<|--EmailPassword
}
/'Configuraciones'/

hide empty members   
hide circle
skinparam classAttributeIconSize 0
@enduml