@startuml Consultar equipo
actor "Cliente" as Client
boundary boundary
control control
collections Equipos as teams 
participant ":Equipo" as team
Client->boundary :getTeams(user)
activate boundary
boundary->control
activate control
control->teams:getTeams(user)
activate teams
loop if user in
  teams->team: getTeam()
  activate team
  teams<<--team
  deactivate team
end
control<<--teams
deactivate teams
boundary<<-- control
deactivate control

Client->boundary :getTeam(team)
boundary -> control 
activate control
control -> teams:getTeam(team)
activate teams
teams -> team:getTeam()
activate team
deactivate team
deactivate teams
deactivate control
deactivate boundary
@enduml