@startuml Crear Equipo
actor "Usuario" as Client
boundary boundary
control control
collections Equipos as teams 
participant ":Equipo" as team
Client->boundary :createTeam(data)
activate boundary
boundary -> control 
activate control
control -> teams:createTeam(data)
activate teams
create team
teams -> team
deactivate teams
deactivate control
deactivate boundary
@enduml