@startuml Editar Equipo
actor "Usuario" as Client
boundary boundary
control control
collections Equipos as teams 
participant ":Equipo" as team
Client->boundary :editTeam(data)
activate boundary
boundary -> control 
activate control
control -> teams:editTeam(data)
activate teams
teams -> team
deactivate teams
deactivate control
deactivate boundary
@enduml