@startuml mostrar Premios
actor "Cliente" as Client
boundary boundary
control control
collections Premios as prizes 
participant ":Premio" as prize
Client->boundary :getPrizes(user)
activate boundary
boundary->control
activate control
control->prizes:getPrizes(user)
activate prizes
loop if user in
  prizes->prize: getPrize()
  activate prize
  prizes<<--prize
  deactivate prize
end
control<<--prizes
deactivate prizes
boundary<<-- control
deactivate control

Client->boundary :getPrize(price)
boundary -> control 
activate control
control -> prizes:getPrize(price)
activate prizes
prizes -> prize:getPrize()
activate prize
deactivate prize
deactivate prizes
deactivate control
deactivate boundary


@enduml